/* Local recovery snapshots. Independent of map packs and their deletion. */
(()=>{
 'use strict';
 const DB='traversee-backups-v1',STORE='snapshots',protectedKey=k=>/^(ravito-|traversee-|bivouac-)/.test(k)&&!k.endsWith('-recovery')&&!k.endsWith('-backup');
 let timer=0,queue=Promise.resolve(),lastSignature='',lastArchive=0;
 const request=r=>new Promise((resolve,reject)=>{r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)});
 function db(name,store){return new Promise((resolve,reject)=>{const r=indexedDB.open(name,1);r.onupgradeneeded=()=>{if(!r.result.objectStoreNames.contains(store))r.result.createObjectStore(store)};r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)})}
 function write(database,store,action){return new Promise((resolve,reject)=>{const tx=database.transaction(store,'readwrite');tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error);tx.onabort=()=>reject(tx.error||Error('Sauvegarde interrompue'));action(tx.objectStore(store))})}
 async function project(){const d=await db('bivouac-scout','projects');try{return await request(d.transaction('projects').objectStore('projects').get('current'))||null}finally{d.close()}}
 async function capture(){const storage={};for(let i=0;i<localStorage.length;i++){const key=localStorage.key(i);if(protectedKey(key))storage[key]=safeStorageGet(key)}return {version:1,at:Date.now(),storage,project:await project()}}
 function valid(s){return !!(s&&s.version===1&&Number.isFinite(s.at)&&s.storage&&typeof s.storage==='object'&&!Array.isArray(s.storage)&&Object.entries(s.storage).every(([k,v])=>protectedKey(k)&&typeof v==='string')&&(!s.project||(s.project.version===2&&typeof s.project.gpx==='string')))}
 async function list(){const d=await db(DB,STORE);try{return (await request(d.transaction(STORE).objectStore(STORE).getAll())).filter(valid).sort((a,b)=>b.at-a.at).filter((s,i,all)=>all.findIndex(other=>JSON.stringify([other.storage,other.project])===JSON.stringify([s.storage,s.project]))===i)}finally{d.close()}}
 async function save(){const snap=await capture(),signature=JSON.stringify([snap.storage,snap.project]);if(signature===lastSignature)return;const d=await db(DB,STORE);try{const previous=await request(d.transaction(STORE).objectStore(STORE).get('latest'));const archive=valid(previous)&&(snap.at-lastArchive>300000);const keys=await request(d.transaction(STORE).objectStore(STORE).getAllKeys());await write(d,STORE,store=>{if(archive)store.put(previous,String(previous.at));store.put(snap,'latest');const historic=keys.filter(k=>k!=='latest').sort();for(const key of historic.slice(0,Math.max(0,historic.length-(archive?2:3))))store.delete(key)});lastSignature=signature;if(archive)lastArchive=snap.at;}finally{d.close()}}
 function schedule(){clearTimeout(timer);timer=setTimeout(()=>{queue=queue.catch(()=>{}).then(save).catch(()=>{})},1200)}
 async function flush(){clearTimeout(timer);queue=queue.catch(()=>{}).then(save);return queue}
 async function restore(snap){if(!valid(snap))throw Error('Sauvegarde invalide');await flush();const before=await capture(),recoveryDb=await db(DB,STORE);try{await write(recoveryDb,STORE,store=>store.put(before,String(before.at)+'-before-restore'))}finally{recoveryDb.close()}const d=await db('bivouac-scout','projects');try{await write(d,'projects',store=>snap.project?store.put(snap.project,'current'):store.delete('current'))}finally{d.close()}const keys=[];for(let i=0;i<localStorage.length;i++){const k=localStorage.key(i);if(/^(ravito-|traversee-|bivouac-)/.test(k)&&!k.endsWith('-recovery'))keys.push(k)}for(const key of keys)if(!(key in snap.storage))safeStorageSet(key,null);for(const [key,value] of Object.entries(snap.storage))if(!safeStorageSet(key,value))throw Error('Stockage indisponible');for(const key of ['ravito-active-validated-v1','ravito-history-v1','ravito-draft-v2'])if(key in snap.storage)safeStorageSet(key+'-backup',snap.storage[key]);location.reload()}
 const root=document.createElement('dialog');root.id='backupDialog';root.innerHTML='<header class="offlineHeader"><h2>Sauvegardes</h2><button type="button" class="offlineClose" aria-label="Fermer">✕</button></header><p id="backupStatus" role="status"></p><div id="backupList"></div><button type="button" class="offlinePrimary" id="backupRestore" disabled>Restaurer</button>';document.body.append(root);
 const q=id=>document.getElementById(id),button=document.createElement('button');button.className='offlineLaunch';button.type='button';button.textContent='Sauvegardes';q('homeGpsPanel').append(button);root.querySelector('.offlineClose').onclick=()=>root.close();let selected=null;
 button.onclick=async()=>{root.showModal();selected=null;q('backupRestore').disabled=true;q('backupList').replaceChildren();q('backupStatus').textContent='Chargement…';try{await flush();const snapshots=await list();q('backupStatus').textContent=snapshots.length?'Copies automatiques sur cet appareil.':'Aucune sauvegarde.';snapshots.forEach((snap,i)=>{const row=document.createElement('label');row.className='backupRow';const radio=document.createElement('input');radio.type='radio';radio.name='snapshot';radio.onchange=()=>{selected=snap;q('backupRestore').disabled=false};const date=new Date(snap.at).toLocaleString('fr-FR',{day:'numeric',month:'numeric',hour:'2-digit',minute:'2-digit'});let km;try{km=JSON.parse(snap.storage['traversee-home-position-v1'])?.km}catch(_){}row.append(radio,document.createTextNode((i===0?'Dernière · ':'')+date+(Number.isFinite(km)?' · km '+Math.round(km):'')));q('backupList').append(row)})}catch(_){q('backupStatus').textContent='Sauvegardes indisponibles.'}};
 q('backupRestore').onclick=async()=>{if(!selected)return;q('backupRestore').disabled=true;try{await restore(selected)}catch(_){q('backupStatus').textContent='Restauration impossible.';q('backupRestore').disabled=false}};
 window.TraverseeBackups={schedule,flush,list,restore,valid};document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='hidden')flush().catch(()=>{})});window.addEventListener('pagehide',()=>flush().catch(()=>{}));schedule();
})();
