/* Verified route packs, entirely inside the application. */
(()=>{
 'use strict';
 const C=TraverseeOfflineCore,base=new URL('./',location.href),metaUrl=id=>new URL('offline-pack/'+id,base).href;
 let controller=null,registration=null,shellReady=false,packs=[],lastFocus,projectRoute=null,deleting=false;
 const root=document.createElement('dialog');root.id='offlineDialog';root.innerHTML='<header class="offlineHeader"><h2>Cartes hors ligne</h2><button class="offlineClose" aria-label="Fermer">✕</button></header><p id="offlineShell" class="offlineState">Vérification…</p><div id="offlinePackList"></div><button id="offlineDeleteAll" class="offlineDeleteAll" hidden>Tout supprimer</button><label id="offlineRouteLabel" hidden>Parcours <select id="offlineRoute"><option value="traverse">Ma traversée</option><option value="project">Mon projet Bivouac</option></select></label><section class="offlineDownload"><div class="offlineDuration" role="group" aria-label="Durée à télécharger"><button id="offlineDay3" type="button">3 jours</button><button id="offlineDay7" type="button">7 jours</button><button id="offlineDay14" type="button">14 jours</button></div><select id="offlineDays" aria-label="Durée à télécharger" hidden><option value="7">7 jours</option><option value="3">3 jours</option><option value="14">14 jours</option></select><p id="offlineEstimate"></p><button class="offlinePrimary" id="offlinePrepare">Télécharger</button><button id="offlineCancel" hidden>Interrompre</button><progress id="offlineProgress" max="1" value="0" hidden></progress><p id="offlineStatus" role="status" aria-live="polite"></p><small id="offlineKeepOpen" hidden>Garde l’app ouverte.</small></section>';document.body.append(root);
 const q=id=>document.getElementById(id),status=s=>q('offlineStatus').textContent=s,fmt=n=>Math.round(n).toLocaleString('fr-FR'),size=b=>(b/1048576).toFixed(0)+' Mo';
 const launch=document.createElement('button');launch.type='button';launch.className='offlineLaunch';launch.textContent='↓ Cartes hors ligne';launch.onclick=()=>open();q('homeGpsPanel').append(launch);
 root.querySelector('.offlineClose').onclick=()=>root.close();root.addEventListener('close',()=>lastFocus?.focus());
 q('offlineDeleteAll').onclick=()=>deleteCards();q('offlineCancel').onclick=()=>controller?.abort();q('offlineDays').onchange=estimate;for(const day of [3,7,14])q('offlineDay'+day).onclick=()=>{q('offlineDays').value=String(day);estimate();};q('offlineRoute').onchange=()=>{estimate();renderPacks()};
 async function timed(url,options={},timeout=20000){const abort=new AbortController(),stop=()=>abort.abort();options.signal?.addEventListener('abort',stop,{once:true});if(options.signal?.aborted)abort.abort();const timer=setTimeout(stop,timeout);try{const r=await fetch(url,{...options,signal:abort.signal});if(!r.ok)throw Error('HTTP '+r.status);return r}finally{clearTimeout(timer);options.signal?.removeEventListener('abort',stop)}}
 async function readPacks(){const cache=await caches.open(C.META_CACHE),keys=await cache.keys();packs=[];const tiles=new Set((await (await caches.open(C.MAP_CACHE)).keys()).map(k=>k.url));for(const key of keys){try{const p=await (await cache.match(key)).json();p.available=p.urls.filter(u=>tiles.has(u)).length;p.complete=p.available===p.urls.length;packs.push(p)}catch(_){}}packs.sort((a,b)=>a.start-b.start);return packs;}
 async function savePack(p){await (await caches.open(C.META_CACHE)).put(metaUrl(p.id),new Response(JSON.stringify(p),{headers:{'Content-Type':'application/json'}}));}
 async function verifyShell(){try{localStorage.setItem('traversee-storage-probe','1');localStorage.removeItem('traversee-storage-probe')}catch(_){throw Error('Stockage des réglages indisponible. Vérifie l’espace disponible sur ton téléphone.')}if(!registration)registration=await navigator.serviceWorker.ready;const worker=navigator.serviceWorker.controller||registration.active;if(!worker)throw Error('Installation en cours. Rouvre ce panneau dans quelques secondes.');const report=await new Promise((resolve,reject)=>{const channel=new MessageChannel(),timer=setTimeout(()=>reject(Error('Vérification de l’application indisponible')),15000);channel.port1.onmessage=e=>{clearTimeout(timer);resolve(e.data)};worker.postMessage({type:'VERIFY_OFFLINE'},[channel.port2])});shellReady=report.version===C.VERSION&&!report.missing.length;if(!shellReady)throw Error('Mise à jour nécessaire : ferme puis rouvre l’app avec du réseau.');return report;}
 function chosenRoute(){return q('offlineRoute').value==='project'&&projectRoute?projectRoute:window.TraverseeRoutes;}
 function currentWindow(){const route=chosenRoute(),km=route===projectRoute?route.progressKm:window.TraverseeHome?.getPosition()?.km||0,start=Math.max(0,km-3),end=Math.min(route.data.routeLengthKm,route.pace.windowEnd(km,Number(q('offlineDays').value))+3);return {route,start,end};}
 function estimate(){const {route,start,end}=currentWindow(),list=C.tiles(route.points,start,end);for(const day of [3,7,14]){q('offlineDay'+day).setAttribute?.('aria-pressed',String(Number(q('offlineDays').value)===day));q('offlineDay'+day).disabled=!!controller||deleting;}const pending=packs.find(p=>p.routeId===route.id&&p.routeVersion===route.version&&Math.floor(p.start*100)===Math.floor(start*100)&&Math.ceil(p.end*100)===Math.ceil(end*100)&&(!p.complete||!p.reliefComplete));q('offlinePrepare').textContent=pending?'Reprendre':'Télécharger';q('offlineEstimate').textContent='Km '+fmt(start)+'–'+fmt(end)+' · Plan IGN';return {route,start,end,list};}
 function renderPacks(){q('offlinePackList').replaceChildren();const relevant=packs.filter(p=>p.routeId===chosenRoute().id&&p.routeVersion===chosenRoute().version);for(const p of relevant){const row=document.createElement('div');row.className='offlinePack';const info=document.createElement('span');info.textContent=(p.complete?'✓ ':'↻ ')+'Km '+fmt(p.start)+'–'+fmt(p.end)+' · '+(p.complete?size(p.bytes||0):Math.floor(p.available/p.urls.length*100)+' % · incomplet');const del=document.createElement('button');del.className='offlineDelete';del.textContent='Supprimer';del.setAttribute?.('aria-label','Supprimer la carte du km '+fmt(p.start)+' au km '+fmt(p.end));del.disabled=!!controller||deleting;del.onclick=()=>deleteCards(p);row.append(info,del);q('offlinePackList').append(row)}if(shellReady){const km=chosenRoute()===projectRoute?projectRoute.progressKm:window.TraverseeHome?.getPosition()?.km||0,here=relevant.some(p=>p.complete&&km>=p.start&&km<=p.end);q('offlineShell').textContent=controller?'Téléchargement en cours':here?'✓ Carte prête ici':relevant.some(p=>p.complete)?'Cartes enregistrées ailleurs':relevant.length?'Téléchargement incomplet':'Aucune carte hors ligne';q('offlineShell').setAttribute?.('data-ready',String(here&&!controller));}q('offlineKeepOpen').hidden=!controller;q('offlineDeleteAll').hidden=!packs.length;q('offlineDeleteAll').disabled=!!controller||deleting;launch.textContent=controller?'↓ Téléchargement en cours':'↓ Cartes hors ligne';}
 async function deleteCards(pack){if(controller||deleting)return;deleting=true;q('offlinePrepare').disabled=true;renderPacks();try{const selected=pack?[pack]:packs,others=packs.filter(p=>!selected.some(x=>x.id===p.id)),keep=new Set(others.flatMap(p=>p.urls)),cache=await caches.open(C.MAP_CACHE);for(const p of selected){for(const u of p.urls)if(!keep.has(u))await cache.delete(u);await (await caches.open(C.META_CACHE)).delete(metaUrl(p.id));await (await caches.open(C.RELIEF_CACHE)).delete(metaUrl(p.id));}if(!pack){for(const name of [C.MAP_CACHE,C.RELIEF_CACHE,'traversee-map-tiles-v1']){const c=await caches.open(name);for(const key of await c.keys())await c.delete(key);}}q('offlineProgress').hidden=true;status('');}catch(_){status('Suppression impossible. Réessaie.');}finally{deleting=false;q('offlinePrepare').disabled=false;await readPacks();renderPacks();estimate();window.dispatchEvent(new Event('traversee-offline-ready'));}}
 async function loadProject(){projectRoute=null;try{const db=await new Promise((resolve,reject)=>{const r=indexedDB.open('bivouac-scout',1);r.onupgradeneeded=()=>{if(!r.result.objectStoreNames.contains('projects'))r.result.createObjectStore('projects')};r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)});const saved=await new Promise((resolve,reject)=>{const r=db.transaction('projects').objectStore('projects').get('current');r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)});db.close();if(saved?.gpx&&saved.mode==='three'){const xml=new DOMParser().parseFromString(saved.gpx,'application/xml'),nodes=xml.getElementsByTagNameNS('*','trkpt'),points=[...(nodes.length?nodes:xml.getElementsByTagNameNS('*','rtept'))].map(p=>[Number(p.getAttribute('lat')),Number(p.getAttribute('lon')),Number(p.getElementsByTagNameNS('*','ele')[0]?.textContent)]);if(points.length>1){const length=C.geometry(points).cum.at(-1);projectRoute={id:C.projectId(saved.gpx),version:'1',points,progressKm:Number(saved.progressKm)||0,data:{routeLengthKm:length},pace:{windowEnd:(km,days)=>C.projectWindowEnd(km,days,length,saved.zones)}}}}}catch(_){}q('offlineRouteLabel').hidden=!projectRoute;}
 async function open(){lastFocus=document.activeElement;if(!controller){status('');q('offlineProgress').hidden=true;}root.showModal();try{await verifyShell();await loadProject();await readPacks();renderPacks();estimate()}catch(e){q('offlineShell').textContent=e.message;status('Vérification impossible. Réessaie.')}}
 async function downloadTiles(list,pack,signal){const cache=await caches.open(C.MAP_CACHE);let index=0,done=0,bytes=0,failed=0;async function work(){while(index<list.length){if(signal.aborted)throw new DOMException('Interrompu','AbortError');const tile=list[index++];let response=await cache.match(tile.url);try{if(!response){let last;for(let attempt=0;attempt<3;attempt++){try{const r=await timed(tile.url,{mode:'cors',signal}),blob=await r.blob(),header=new Uint8Array(await blob.slice(0,8).arrayBuffer());if(header[0]!==137||header[1]!==80||header[2]!==78||header[3]!==71)throw Error('Image IGN invalide');response=new Response(blob,{headers:{'Content-Type':'image/png','Content-Length':String(blob.size)}});await cache.put(tile.url,response.clone());break}catch(e){if(signal.aborted)throw e;last=e}}if(!response)throw last;}bytes+=(await response.blob()).size;}catch(e){if(signal.aborted)throw e;failed++;}done++;q('offlineProgress').value=done/list.length;status(Math.floor(done/list.length*100)+' %'+(failed?' · à reprendre':''));}}
 const result=await Promise.allSettled(Array.from({length:4},work));pack.bytes=bytes;pack.updatedAt=Date.now();await savePack(pack);if(signal.aborted)throw new DOMException('Interrompu','AbortError');if(result.some(r=>r.status==='rejected')||failed)throw Error('Téléchargement incomplet.');}
 async function prepareRelief(route,pack,signal){const cache=await caches.open(C.RELIEF_CACHE),previous=await cache.match(metaUrl(pack.id)),record=previous?await previous.json():{startTick:Math.floor(pack.start*20),endTick:Math.ceil(pack.end*20),rows:[]},g=C.geometry(route.points);let missing=[];for(let tick=record.startTick;tick<=record.endTick;tick++){if(!record.rows[tick-record.startTick])missing.push(tick);}for(let i=0;i<missing.length;i+=150){if(signal.aborted)throw new DOMException('Interrompu','AbortError');const ticks=missing.slice(i,i+150),coords=ticks.flatMap(t=>C.reliefPoints(g,t/20));status('Préparation du relief : '+fmt(Math.min(i+150,missing.length))+' / '+fmt(missing.length));const response=await timed('https://data.geopf.fr/altimetrie/1.0/calcul/alti/rest/elevation.json',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({lon:coords.map(p=>p.lng.toFixed(7)).join('|'),lat:coords.map(p=>p.lat.toFixed(7)).join('|'),resource:'ign_rge_alti_wld',delimiter:'|',zonly:'false',measures:'false'}),signal},30000);const data=await response.json();if(data.elevations?.length!==coords.length)throw Error('Relief IGN incomplet');const values=data.elevations.map(p=>Number(p.z));if(!values.every(z=>Number.isFinite(z)&&z>-99999))throw Error('Altitudes IGN manquantes');ticks.forEach((tick,n)=>record.rows[tick-record.startTick]=values.slice(n*3,n*3+3));await cache.put(metaUrl(pack.id),new Response(JSON.stringify(record),{headers:{'Content-Type':'application/json'}}));}pack.reliefComplete=record.rows.filter(Boolean).length===record.endTick-record.startTick+1;await savePack(pack);}
 async function downloadPictures(signal){const report=await verifyShell(),cache=await caches.open('traversee-app-'+report.version);let missing=0;for(let i=0;i<49;i++){const url=new URL('images/meals/meal-'+String(i).padStart(2,'0')+'.webp',base).href;if(await cache.match(url))continue;try{const r=await timed(url,{signal});await cache.put(url,r)}catch(e){if(signal.aborted)throw e;missing++}}return missing;}
 async function prepare(){if(controller||deleting)return;controller=new AbortController();renderPacks();q('offlinePrepare').disabled=true;q('offlineDays').disabled=true;q('offlineRoute').disabled=true;q('offlineCancel').hidden=false;q('offlineProgress').hidden=false;q('offlineProgress').value=0;estimate();let pack;try{await verifyShell();if(!navigator.onLine)throw Error('Connexion nécessaire pour télécharger.');try{await navigator.storage?.persist?.()}catch(_){}status('Enregistrement des images des menus…');const missingPictures=await downloadPictures(controller.signal);const {route,start,end,list}=estimate(),id=route.id+'-'+route.version+'-'+Math.floor(start*100)+'-'+Math.ceil(end*100);await readPacks();pack=packs.find(p=>p.id===id)||{id,routeId:route.id,routeVersion:route.version,start,end,urls:list.map(t=>t.url),createdAt:Date.now(),bytes:0};await savePack(pack);const stored=new Set((await (await caches.open(C.MAP_CACHE)).keys()).map(k=>k.url)),remaining=list.filter(t=>!stored.has(t.url)).length;const storage=await navigator.storage?.estimate?.();if(storage?.quota&&storage.quota-storage.usage<remaining*80000)throw Error('Espace insuffisant. Supprime des cartes ou choisis 3 jours.');await downloadTiles(list,pack,controller.signal);await readPacks();if(!packs.find(p=>p.id===id)?.complete)throw Error('Vérification incomplète des cartes. Reprends le téléchargement.');let reliefMessage='';try{await prepareRelief(route,pack,controller.signal)}catch(e){if(controller.signal.aborted)throw e;reliefMessage=' Relief à reprendre.';}status('✓ Téléchargé · '+size(pack.bytes)+'.'+reliefMessage+(missingPictures?' '+missingPictures+' images de menus restent à télécharger.':''));window.dispatchEvent(new Event('traversee-offline-ready'));}catch(e){status(controller.signal.aborted?'Téléchargement interrompu.':e.message);}finally{controller=null;q('offlinePrepare').disabled=false;q('offlineDays').disabled=false;q('offlineRoute').disabled=false;q('offlineCancel').hidden=true;q('offlineProgress').hidden=true;await readPacks();renderPacks();estimate();}}
 q('offlinePrepare').onclick=prepare;
 async function points(){const r=await fetch(new URL(TraverseeRoutes.id==='brenne'?'home-pois-brenne.json?v='+C.VERSION:'home-pois.json?v='+C.VERSION,base));if(!r.ok)throw Error('Points embarqués indisponibles');const data=await r.json();const shelters=await (await fetch(new URL('shelter-points.json',base))).json();return [...data.water,...data.camping.map(p=>({...p,type:'Camping'})),...shelters];}
 async function relief(kms,route=TraverseeRoutes){await readPacks();const usable=packs.filter(p=>p.routeId===route.id&&p.routeVersion===route.version&&p.reliefComplete&&kms[0]>=p.start&&kms.at(-1)<=p.end);const cache=await caches.open(C.RELIEF_CACHE);for(const p of usable){const response=await cache.match(metaUrl(p.id));if(!response)continue;const r=await response.json(),z=[];for(const km of kms){const f=km*20-r.startTick,i=Math.floor(f),a=r.rows[i],b=r.rows[Math.min(i+1,r.rows.length-1)];if(!a||!b)throw Error('Relief hors couverture');for(let j=0;j<3;j++)z.push(a[j]+(b[j]-a[j])*(f-i));}return z;}throw Error('Relief hors ligne non téléchargé sur cette zone');}
 window.TraverseeOffline={points,relief,open,readPacks};
 if('serviceWorker' in navigator){navigator.serviceWorker.register('./sw.js',{updateViaCache:'none'}).then(r=>{registration=r;r.update().catch(()=>{})}).catch(e=>{q('offlineShell').textContent='Préparation indisponible : '+e.message});}
 window.addEventListener('traversee-storage-error',()=>{shellReady=false;q('offlineShell').textContent='Stockage indisponible : les derniers réglages ne sont pas enregistrés.';launch.textContent='Vérifier le stockage hors ligne';});
 async function coverageNotice(){if(navigator.onLine)return;await readPacks();const km=window.TraverseeHome?.getPosition()?.km||0,covered=packs.some(p=>p.complete&&p.routeId===TraverseeRoutes.id&&p.routeVersion===TraverseeRoutes.version&&km>=p.start&&km<=p.end);if(!covered){const message=q('homeMapMessage');message.textContent='Carte non téléchargée ici. Les points et la trace restent disponibles.';message.hidden=false;}launch.textContent='↓ Mes cartes hors ligne';}
 window.addEventListener('offline',coverageNotice);window.addEventListener('traversee-home-position',coverageNotice);window.addEventListener('traversee-offline-ready',coverageNotice);coverageNotice().catch(()=>{});
})();
